"use client";

import "../globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";


const navLinks = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forgot Password", href: "/forgot-password" },
];

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  return (
    <div>
      {navLinks.map((link) => {
        const isActive =
          pathName === link.href ||
          (pathName.startsWith(link.href) && link.href !== "/");
        return (
          <Link
            className={isActive ? "text-[purple]" : "text-[blue]"}
            href={link.href}
            key={link.name}
          >
            {link.name} <br />
          </Link>
        );
      })}
      {children}
    </div>
  );
}

// import './globals.css'

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <header className="text-[30px] bg-[pink] py-[20px] my-[10px]">
//           Header
//         </header>
//         {children}
//         <footer className="text-[30px] bg-[grey] py-[20px] my-[10px]">
//           Footer
//         </footer>
//         </body>
//     </html>
//   )
// }
