import './globals.css'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: {
    default: 'Next.js proj',
    template: '%s | Codevol',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="text-[30px] bg-[grey] py-[20px] my-[10px] text-center">
          Header
        </header>
        {children}
        <footer className="text-[30px] bg-[grey] py-[20px] my-[10px] text-center">
          Footer
        </footer>
        </body>
    </html>
  )
}