import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="text-[30px] bg-[pink] py-[20px] my-[10px]">
          Header
        </header>
        {children}
        <footer className="text-[30px] bg-[grey] py-[20px] my-[10px]">
          Footer
        </footer>
        </body>
    </html>
  )
}
